#config/routes.yaml

homepage:
  path: /
  controller: App\Controller\BlogController::index

article_add:
  path: /add
  controller: App\Controller\BlogController::add

comment_add:
  path: /comment/{id}
  controller: App\Controller\UserController::addComment
  requirements:
    id: '\d+'

article_show:
  path: /show/{id}
  controller: App\Controller\BlogController::show

article_own_event:
  path: /ownEvent
  controller: App\Controller\UserController::ownEvent

article_edit:
  path: /edit/{id}
  controller: App\Controller\BlogController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\BlogController::remove
  requirements:
    id: '\d+'

user_remove:
  path: /removeUser/{id}
  controller: App\Controller\SecurityController::removeUser
  requirements:
    id: '\d+'

user_verify:
  path: /verifyUser/{id}
  controller: App\Controller\SecurityController::verifyUser
  requirements:
    id: '\d+'

comment_remove:
  path: /removeComment/{id}
  controller: App\Controller\UserController::removeComment
  requirements:
    id: '\d+'

article_createAccount:
  path: /register
  controller: App\Controller\RegistrationController::register

admin:
  path: /admin
  controller: App\Controller\BlogController::admin